// Code generated by entc, DO NOT EDIT.

package poll

import (
	"time"
)

const (
	// Label holds the string label denoting the poll type in the database.
	Label = "poll"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerid holds the string denoting the ownerid field in the database.
	FieldOwnerid = "ownerid"
	// FieldTopic holds the string denoting the topic field in the database.
	FieldTopic = "topic"
	// FieldOptions holds the string denoting the options field in the database.
	FieldOptions = "options"
	// FieldCreatetime holds the string denoting the createtime field in the database.
	FieldCreatetime = "createtime"
	// FieldModifytime holds the string denoting the modifytime field in the database.
	FieldModifytime = "modifytime"
	// Table holds the table name of the poll in the database.
	Table = "polls"
)

// Columns holds all SQL columns for poll fields.
var Columns = []string{
	FieldID,
	FieldOwnerid,
	FieldTopic,
	FieldOptions,
	FieldCreatetime,
	FieldModifytime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOwnerid holds the default value on creation for the "ownerid" field.
	DefaultOwnerid int
	// DefaultTopic holds the default value on creation for the "topic" field.
	DefaultTopic string
	// DefaultCreatetime holds the default value on creation for the "createtime" field.
	DefaultCreatetime func() time.Time
	// DefaultModifytime holds the default value on creation for the "modifytime" field.
	DefaultModifytime func() time.Time
)
