// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Poll is the predicate function for poll builders.
type Poll func(*sql.Selector)

// Result is the predicate function for result builders.
type Result func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
